### ISSUE TITLE
Bug with changing hash url manually

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/reactive-router#5]
There is a bug inside Page JS, it is missing the "onhashchange" listener. I have created a pull here: https://github.com/visionmedia/page.js/pull/301 with a suggested fix.

If this is not pulled into the repo I think we need to build our own. Page JS does include some unnecessary functionality. So yeah, can make this really minimalistic.

All we really need is hashchange and popstate listeners, maybe the https://www.npmjs.com/package/history would be a good fit.

**Comment by gcanti** [comment]
> If this is not pulled into the repo I think we need to build our own. Page JS does include some unnecessary functionality. So yeah, **can make this really minimalistic**.

Hi @christianalfoni, 

I wrote a router with a minimal API. It's headless, it just handles the dispatching functionality:

API:

**constructor(routes)**

Where `routes: {[key: String]: Function}` is a dictionary `path -> handler` and `handler` has the following signature:

``` js
(context: Context) -> any
```

`Context` is a struct with the following fields:
- `path: String`
- `params: : {[key: String]: String}`
- `query: {[key: String]: String}`
- `payload: Any` (optional)

Example:

``` js
var router = new Router({
  '/user/:id': fetchUser
});
```

The router could have an additional `addRoute(path, handler)` API if the order in which the routes are scanned is important.

Example:

``` js
router
  .addRoute('/users', fetchUsers);
  .addRoute('/user/:id', fetchUser);
```

**dispatch(url, [payload])**

Example:

``` js
router.dispatch('/user/123');

/*
will call `fetchUser` with the following argument (a `Context` instance):
{
  path: '/user/123',
  params: { id: '123' },
  query: {}
}
*/
```

Here the code 100 ES5 LOC (the only hard dependency is `path-to-regexp` AFAIK also used in the express project):

https://gist.github.com/gcanti/8b262cb2077e0b98620d

Now, with such a basic router implementation, one could add features on top:
- hash router
- history router
- handle nesting...and so on

**Example: building a hash router**

``` js
Router.prototype.set = function (url) {
  location.hash = '#' + url;
};

window.onhashchange = function () {
  const url = location.hash.substr(1);
  if (url !== state.url) {
    router.dispatch(url);
  }
};

const router = ...

state.on('change', function (state) {
  router.set(state.url);
});
```

Hope it can be helpful.

Giulio

**Comment by bfitch** [comment]
I'm experiencing the same problem with non-hash url changes. Callbacks are not being triggered when manually changing `http://localhost:8080/foo` to `http://localhost:8080/bar`. Callbacks _are_ firing on links (`<a href="/bar">`), though.

**Comment by christianalfoni** [comment]
Okay, cool, looking forward to your barebone implementation :-) It will be really great to get this `reactive-router` on track, as it is kind of the router Cerebral should use. 

I saw there is traction on React-Router too actually, decoupling it from the components. But I do not think it will handle updating the url from the state store, which is important to get "all the way".

Anyways, let me know if you need to discuss something etc. I also added you as a contributor on the repo, so feel free to create a branch and push it up directly.

**Comment by bfitch** [comment]
Just pushed up a first implementation with [rackt/history](https://github.com/rackt/history) to the `add_rackt_history` branch. No dependencies except for the history package. Let me know what you all think!

**Comment by christianalfoni** [comment]
https://github.com/christianalfoni/reactive-router/issues/8
