### ISSUE TITLE
What direction to take

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/reactive-router#8]
Hi!

I think we need to choose a direction with this project. The really cool thing about `cerebral-router` now is how it binds urls to functions and I am thinking this would be great to introduce to other projects too.

This would mean that `reactive-router` would use `addressbar` and `url-mapper` to bind urls something like:

``` js
var router = Router({
  onlyHash: true
});

var myAction = router.bind('/', myAction);
```

So when the url is changed it will trigger the action it is bound to, but also if you run the action itself the url will change.

**Comment by bebraw** [comment]
I gave reactive-router a quick go today while developing a [little playground](https://github.com/survivejs/react-demos). I have just two major problems in mind (might be possible with the current setup even):
- How to deal with dynamic loading? I pushed this to `componentDidMount` at my demo but I'm not sure if this is entirely correct.
- How to animate transitions between urls?

Perhaps it would be useful to design a couple of basic demos and then guide the development based on that?

**Comment by christianalfoni** [comment]
I will deprecate this repo and point to addressbar and url-mapper and encourage exploring how routing can be done. We have used experiences here in the Cerebral Router, which is one example of how we can take a different approach on routing :-)
