### ISSUE TITLE
How to deal with static generation?

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/reactive-router#9]
See [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin). Is there a way to achieve something similar with _reactive-router_?

**Comment by christianalfoni** [comment]
With static apps I do not think you need a router really? You basically want to use React to iterate a set of urls and produce different outputs? I suppose you could just pass in a prop to the render method and with that prop decide what components to render?

**Comment by bebraw** [comment]
Yeah, that's a valid point. Just having means to **extract** path definition of some sort is enough. I agree this can be solved outside of a router. In Antwar it's actually mixed. We have a rough route definition at react-router and describe exact routes through configuration and `require.context`.

I played around with [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin) and react-router but it's brittle at best. It's easy to get if fail in a way or another through dependencies (missing `navigator` etc.).

**Comment by christianalfoni** [comment]
Maybe the https://github.com/christianalfoni/url-mapper project could be of some assistance? Create a plugin to do exactly what you want?

**Comment by bebraw** [comment]
That could work. Most likely I'll just stab Antwar to suit my purposes and forget about static-site-generator-webpack-plugin altogether.

Feel free to close if you think route extraction goes beyond the scope of reactive-router. :8ball:

**Comment by christianalfoni** [comment]
At least for now, have to sit down and choose a path for it first. Want to bring in concepts from Cerebral-Router where you bind a url to a function. Does not matter if a url triggers or you call the bound function. It will update the addressbar :)
